### ISSUE TITLE
load img

### ISSUE THREAD

**Issue by feiyu1001** [NightWhistler/HtmlSpanner#35]
android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5748)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1166)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
            at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
            at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:409)
            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:362)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:308)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
            at java.net.URL.openStream(URL.java:470)
            at net.nightwhistler.htmlspanner.handlers.ImageHandler.loadBitmap(ImageHandler.java:69)
            at net.nightwhistler.htmlspanner.handlers.ImageHandler.handleTagNode(ImageHandler.java:49)
            at net.nightwhistler.htmlspanner.HtmlSpanner.applySpan(HtmlSpanner.java:345)
            at net.nightwhistler.htmlspanner.HtmlSpanner.applySpan(HtmlSpanner.java:339)
            at net.nightwhistler.htmlspanner.HtmlSpanner.applySpan(HtmlSpanner.java:339)
            at net.nightwhistler.htmlspanner.HtmlSpanner.fromTagNode(HtmlSpanner.java:260)
            at net.nightwhistler.htmlspanner.HtmlSpanner.fromHtml(HtmlSpanner.java:201)
            at com.example.htmltest.MainActivity$1.run(MainActivity.java:25)
            at android.app.Activity.runOnUiThread(Activity.java:5052)
            at com.example.htmltest.MainActivity.onCreate(MainActivity.java:21)
            at android.app.Activity.performCreate(Activity.java:5600)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5748)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)

**Comment by feiyu1001** [comment]
targetSdkVersion > 8 got this error；targetSdkVersion< =8  no error
<uses-sdk
        android:minSdkVersion="17"
        android:targetSdkVersion="22" />

**Comment by feiyu1001** [comment]
targetSdkVersion > 8 got this error；targetSdkVersion< =8  no error
<uses-sdk
        android:minSdkVersion="17"
        android:targetSdkVersion="22" />

**Comment by harry0880** [comment]
Use AsyncTask...

**Comment by acuna-personal** [comment]
It's not a library bug. Images loads dynamicaly from server, so you need to use a native Android `AsuncTask` class to load it.
